site_name: flake8-cached
site_description: A wrapper around flake8's cli that uses cache at file level
site_author: Noortheen Raja 

repo_url: https://github.com/jnoortheen/flake8-cached
edit_uri: https://github.com/jnoortheen/flake8-cached/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
